import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Steps from "@/components/Steps";
import Context from "@/components/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-300`}>
        <Context>
          <main className="container mx-auto grid max-w-[1440px] grid-cols-8">
            <Steps />
            {children}
          </main>
        </Context>
      </body>
    </html>
  );
}
